name: Test and Build

on:
  push:
    branches:
      - KillYourMaster
  pull_request:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          npm ci
          npx arc hydrate

      - name: Test the application
        run: |
          npm run lint
          npm test

      - name: Build the application
        run: npm run build
