name: Test and Build

on: [push, pull_request]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          npm ci
          npx arc hydrate
          npm test

      - name: Test the application
        run: |
          npm run lint
          npm test

      - name: Build the application
        run: npm run build
